### ISSUE TITLE
Tracking issue for `parse` module

### ISSUE THREAD

**Issue by mbrobbel** [substrait-io/substrait-rs#157]
This is a tracking issue for a `parse` module in the Substrait crate.

Some requirements of Substrait can not be expressed via Protobuf definition or schema files. A `parse` module can provide types for the generated types, that when constructed are known to be checked. This enables producers and consumers to skip redundant checking of invariants described by the specification.

I want to propose incrementally building the `parse` module i.e. split up the intial work in #89 to help reviewers and to encourage collaboration.

# Parser progress

## Proto

- [ ] [`PlanVersion`](https://docs.rs/substrait/latest/substrait/proto/struct.PlanVersion.html)
  - [ ] [`Version`](https://docs.rs/substrait/latest/substrait/proto/struct.Version.html)
- [ ] [`Plan`](https://docs.rs/substrait/latest/substrait/proto/struct.Plan.html)
  - [ ] [`Version`](https://docs.rs/substrait/latest/substrait/proto/struct.Version.html)
  - [ ] ...
- [ ]   [`PlanRel`](https://docs.rs/substrait/latest/substrait/proto/struct.PlanRel.html)
  - [ ] [`RelType`](https://docs.rs/substrait/latest/substrait/proto/plan_rel/enum.RelType.html)
    - [ ] [`Rel`](https://docs.rs/substrait/latest/substrait/proto/struct.Rel.html)
      - [ ] ...
    - [ ] [`RelRoot`](https://docs.rs/substrait/latest/substrait/proto/struct.RelRoot.html)
      - [ ] ...
- [ ] [`ExtendedExpression`](https://docs.rs/substrait/latest/substrait/proto/struct.ExtendedExpression.html)
  - [ ] [`Version`](https://docs.rs/substrait/latest/substrait/proto/struct.Version.html)
  - [ ] ...

## Text

- [ ] [`SimpleExtensions`](https://docs.rs/substrait/latest/substrait/text/simple_extensions/struct.SimpleExtensions.html)
  - [ ] ...

# Other tasks

- [ ] Add the `parse` module with traits to drive the parser
- [ ] Include core extensions in crate, so they can be added to a parse context
- [ ] Add a `parser` cli
- [ ] Add bindings to support using the parse module in other languages

**Comment by holicc** [comment]
Any plans to support parsing SQL directly?

**Comment by mbrobbel** [comment]
> Any plans to support parsing SQL directly?

Absolutely. I think a logical next step would be to add builders for the parsed types, which could be used to build a SQL to substrait tool.

**Comment by holicc** [comment]
> > Any plans to support parsing SQL directly?
> 
> Absolutely. I think a logical next step would be to add builders for the parsed types, which could be used to build a SQL to substrait tool.

Cool! I'm interested in this. Anything I can do?

**Comment by mbrobbel** [comment]
> > > Any plans to support parsing SQL directly?
> > 
> > 
> > Absolutely. I think a logical next step would be to add builders for the parsed types, which could be used to build a SQL to substrait tool.
> 
> Cool! I'm interested in this. Anything I can do?

If you want to contribute: this task would be a good one. Or else figuring out an ergonomic design for the builders.
